#!/bin/sh

# source packages file
. ./packages

distdir="$(xdistdir)"

cd "$distdir" || exit

# update source repository
git pull upstream master

# update masterdir
if [ ! -d masterdir ] ; then
	./xbps-src binary-bootstrap
else
	./xbps-src bootstrap-update
fi

repos="--repository=$distdir/hostdir/binpkgs
       --repository=$distdir/hostdir/binpkgs/nonfree
       --repository=$distdir/hostdir/binpkgs/multilib
       --repository=$distdir/hostdir/binpkgs/multilib/nonfree
       --repository=$distdir/hostdir/binpkgs/debug"

# update packages
xbulk $(xbps-checkvers -f '%n' -i $repos -D "$distdir" -m $pkgs)
