#!/bin/bash
#
# XBPS-builder

# source configuration
if [ ! -f conf ]; then
	echo "No configuration found." >/dev/stderr
	exit
fi
source ./conf

# update distdir
cd "$distdir" || exit
update_distdir || exit

declare -A bootstrap_used
for arch in $archs; do
	bootstrap_used[${bootstrap[$arch]}]=1
done

# update masterdirs
for bootstrap_arch in "${!bootstrap_used[@]}"; do
	_masterdir=${masterdir[$bootstrap_arch]}
	./xbps-src -m $_masterdir binary-bootstrap $bootstrap_arch
	./xbps-src -m $_masterdir bootstrap-update
done

# add repositories
binpkgs="hostdir/binpkgs"
repos=(
	"$binpkgs"
	"$binpkgs/nonfree"
	"$binpkgs/multilib"
	"$binpkgs/multilib/nonfree"
	"$binpkgs/debug"
)

repos_opt=""
for repo in ${repos[@]}; do
	repos_opt+=" --repository=$repo"
done

# update packages
for arch in $archs; do
	bootstrap_arch=${bootstrap[$arch]}
	arch_opt="-m ${masterdir[$bootstrap_arch]}"
	if [[ "$arch" != "$bootstrap_arch" ]]; then
		arch_opt+=" -a $arch"
	fi
	for pkg in $(XBPS_TARGET_ARCH=$arch xbps-checkvers -f '%n' -i $repos_opt -D "$distdir" -m $packages); do
		./xbps-src show-avail $pkg $arch_opt && ./xbps-src pkg $pkg $arch_opt
	done
done
